name: Continuous delivery pipeline

trigger:
  - master

pool:
  vmImage: ubuntu-latest

stages:
  - template: templates/build.yml
    parameters:
      shouldPublishArtifact: true
      artifactName: 'app-artifact'
      artifactPath: '$(Build.ArtifactStagingDirectory)/published'
