name: Build and test
run-name: ${{github.actor}} is running build-test workflow 🚀

on:
  push:
    branches: new_ci_cd
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run unit tests
        run: dotnet test ${{ env.UNIT_TESTS_PATH }}
      - name: Run integration tests
        if: ${{env.CAN_RUN_INTEGRATION_TESTS == 'true'}}
        run: dotnet test ${{ env.INTEGRATION_TESTS_PATH }}
