name: Build and test
run-name: ${{github.actor}} is running build-test workflow 🚀

on:
  push:
    branches: integration_tests
  pull_request:
    branches: master
  workflow_dispatch:

jobs:
  Build-and-test:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.5.2
      - name: Setup .NET 7 SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '7.x.x'
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Run unit tests
        run: dotnet test '${{ vars.UNIT_TESTS_PATH }}' --no-build
      - name: Run integration tests
        if: ${{vars.CAN_RUN_INTEGRATION_TESTS == 'true'}}
        env:
          ConnectionStrings__DefaultConnectionString: ${{ secrets.CONNECTIONSTRING_INTEGRATION_TESTS }}        
        run: dotnet test '${{ vars.INTEGRATION_TESTS_PATH }}' --no-build
